### ISSUE TITLE
https://github.com/apps/repo-lockdown isn't working

### ISSUE THREAD

**Issue by lukateras** [dessant/repo-lockdown#1]
Judging by https://github.com/prism-break/prism-break/pull/2034 and some other issues, it seems that repo-lockdown GitHub app has stopped working somewhere around 4 days ago.

**Comment by dessant** [comment]
It seems the config was not added to the repo.

https://github.com/dessant/repo-lockdown#configuration

**Comment by dessant** [comment]
I remember you added it correctly at the time, maybe a merge from upstream removed it.

**Comment by lukateras** [comment]
Oh, got it. Thanks :-) Sorry for bugging you!
