### ISSUE TITLE
How to install on a different GitHub?

### ISSUE THREAD

**Issue by the-nose-knows** [dessant/repo-lockdown#2]
I would like to use your Repo Lockdown app on a GitHub Enterprise instance. How can I go about setting that up?

**Comment by dessant** [comment]
You may have some luck with configuring and running your own instance of the app, but I don't have a GitHub Enterprise license to test.

https://github.com/probot/probot/blob/master/docs/github-api.md#github-enterprise

**Comment by dessant** [comment]
These are the docs for deploying Probot apps: https://probot.github.io/docs/deployment/

The following permissions are required for the GitHub app: https://github.com/dessant/repo-lockdown/blob/master/docs/deploy.md
