### ISSUE TITLE
Does it work for single branch or the whole repository?

### ISSUE THREAD

**Issue by rokibhasansagar** [dessant/repo-lockdown#3]
I wanted to lock PRs in master branch of a repo, but want to allow on other branches.
Will this app help?

**Comment by dessant** [comment]
No, all branches are locked. I plan to port this app to GitHub actions in about a month, and I'll look into adding this feature.

**Comment by rokibhasansagar** [comment]
> No, all branches are locked. I plan to port this app to GitHub actions in about a month, and I'll look into adding this feature.

I'll be glad, and I think more users will also be happy to use that feature.
Thanks 😀
