### ISSUE TITLE
Org-wide config?

### ISSUE THREAD

**Issue by dpage** [dessant/repo-lockdown#7]
Hi

The PostgreSQL project has been using the legacy app to close PRs to all the mirror repos we keep on Github (https://github.com/postgres). I noticed today that the we've had a couple of PRs that haven't been closed, and realised after digging in that you've moved the project to use Github Actions, and deprecated the old Probot app.

For various reasons it's not feasible for us to add a .github directory to the upstream source trees. Are there any plans to support org-wide configuration as we used to use?

**Comment by dessant** [comment]
It's not yet possible to globally declare workflows in the `.github` repository, a workflow file must always be present in the main branch of the target repository.

https://github.community/t/plans-to-support-global-workflows-in-github-repository/17899

**Comment by dessant** [comment]
In your case limiting interactions for the repository may be a solution: https://docs.github.com/en/communities/moderating-comments-and-conversations/limiting-interactions-in-your-repository

The limit is lifted after 6 months, and the option needs to be enabled again.

**Comment by dpage** [comment]
Thanks for the reply. I did look at limiting interactions, but that seems like it's really only useful as a temporary fix - it seems quite likely we'd forget to reset it periodically!

I guess we'll have to go with the backup solution; a few API calls from a script run from cron on one of our boxes :-(
