### ISSUE TITLE
Node.js 12 actions are deprecated; The `set-output` command is deprecated

### ISSUE THREAD

**Issue by bubbasnmp** [dessant/repo-lockdown#8]
action
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: dessant/repo-lockdown

action
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by dessant** [comment]
Please update to Repo Lockdown v3.0.0.

```yaml
    steps:
      - uses: dessant/repo-lockdown@v3
```
